### ISSUE TITLE
Expose underlying Topshelf ServiceConfigurator

### ISSUE THREAD

**Issue by igitur** [rebus-org/Topper#5]
Hi,

Firstly, thanks for this project and the whole Rebus suite.

I'd like to have more control over my Topshelf installation. And for that I need to get the underlying ServiceConfigurator instance through Topper. 

I can submit a PR to do this, but would like to check the exact API with you first and whether you're OK with the concept in the first place.

**Comment by igitur** [comment]
@mookid8000 Any comments? Otherwise I'll go ahead with a PR as I think it should work.

**Comment by mookid8000** [comment]
Sorry for the long latency!

How would you expose the `ServiceConfigurator`?

**Comment by igitur** [comment]
Sorry, I meant `HostConfigurator`, not `ServiceConfigurator`. 

Draft proposal at #6. I think the method and variable names need to be discussed a bit. But this simple adjustment gets the job done for me to control my Topshelf instance in finer detail.
